import RequireAuth from "@/components/utils/requireAuth";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return <RequireAuth>{children}</RequireAuth>;
}
