import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import Provider from "@/redux/provider";
import Setup from "../components/utils/Setup";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "SaaS Boilerplate",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	const className = [cn("h-full", inter.className)];
	return (
		<html lang="en" className="min-h-max h-full">
			<body className={className}>
				<Provider>
					<Setup />
					<div>{children}</div>
					{/* className="mx-auto max-w-xl px-2 sm:px-6 lg:px-8 py-8" */}
				</Provider>
			</body>
		</html>
	);
}
