const LOGIN_URL = "/auth/login";
const LOGIN_REDIRECT_URL = "/dashboard";
const PASSWORD_RESET_SUCCESSFUL_REDIRECT_URL = LOGIN_URL;
const PASSWORD_RESET_REDIRECT_URL = LOGIN_URL;
const REGISTRATION_REDIRECT_URL = LOGIN_URL;
